"""Initial migration with all current tables

Revision ID: 9bf830f9d18e
Revises: 
Create Date: 2025-12-02 11:25:14.427596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9bf830f9d18e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batchrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_api_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('output_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_counts', sa.JSON(), nullable=True),
    sa.Column('batch_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('batch_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batchrequest_batch_api_id'), 'batchrequest', ['batch_api_id'], unique=True)
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cv_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matches', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_cv_id'), 'prediction', ['cv_id'], unique=False)
    op.create_index(op.f('ix_prediction_prediction_id'), 'prediction', ['prediction_id'], unique=True)
    op.drop_index(op.f('idx_jobs_embedding'), table_name='jobs', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('jobs_embedding_idx'), table_name='jobs', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('jobs')
    op.add_column('cv', sa.Column('embedding_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('cv', sa.Column('is_latest', sa.Boolean(), nullable=False))
    op.add_column('cv', sa.Column('last_analyzed', sa.DateTime(), nullable=True))
    op.add_column('cv', sa.Column('last_updated', sa.DateTime(), nullable=False))
    op.alter_column('cv', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"))
    op.drop_index(op.f('cv_embedding_idx'), table_name='cv', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('cv_embedding_idx1'), table_name='cv', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_cv_embedding'), table_name='cv', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.add_column('job', sa.Column('embedding_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('job', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"))
    op.drop_index(op.f('job_embedding_idx'), table_name='job', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('job_embedding_idx1'), table_name='job', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('job_job_id_idx'), table_name='job')
    op.drop_index(op.f('job_job_id_idx1'), table_name='job')
    op.add_column('userinteraction', sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('userinteraction', sa.Column('interaction_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinteraction', 'interaction_metadata')
    op.drop_column('userinteraction', 'strategy')
    op.create_index(op.f('job_job_id_idx1'), 'job', ['job_id'], unique=False)
    op.create_index(op.f('job_job_id_idx'), 'job', ['job_id'], unique=False)
    op.create_index(op.f('job_embedding_idx1'), 'job', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('job_embedding_idx'), 'job', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('job', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"))
    op.drop_column('job', 'embedding_status')
    op.create_index(op.f('idx_cv_embedding'), 'cv', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('cv_embedding_idx1'), 'cv', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('cv_embedding_idx'), 'cv', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('cv', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"))
    op.drop_column('cv', 'last_updated')
    op.drop_column('cv', 'last_analyzed')
    op.drop_column('cv', 'is_latest')
    op.drop_column('cv', 'embedding_status')
    op.create_table('jobs',
    sa.Column('id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('jobs_pkey'))
    )
    op.create_index(op.f('jobs_embedding_idx'), 'jobs', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_index(op.f('idx_jobs_embedding'), 'jobs', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_prediction_prediction_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_cv_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_batchrequest_batch_api_id'), table_name='batchrequest')
    op.drop_table('batchrequest')
    # ### end Alembic commands ###
